### ISSUE TITLE
Don't expect the login to be an email address

### ISSUE THREAD

**Issue by nul800sebastiaan** [cheeseytoastie/UmbMembersFullTutorial#3]
https://github.com/cheeseytoastie/UmbMembersFullTutorial/blob/master/Controllers/Account/MemberRegisterSurfaceController.cs#L33

Not necessarily true, you can still register members with a plain old username, it doesn't need to be an email address. I know this works in all of this example code as you do store everything as an email to login and validate the user but it's not required.

**Comment by nul800sebastiaan** [comment]
Ps. You have a `MemberHelper.EmailIsInUse` method you could use here ;-)

**Comment by cheeseytoastie** [comment]
I've updated the comment. I think most sites tend to use email these days so hopefully the comment is enough?

**Comment by nul800sebastiaan** [comment]
Not just for legacy sites, anyone can choose to use non-email usernames. :-)

**Comment by cheeseytoastie** [comment]
Not legacy sites as in old umbraco (though my previous comment did imply that).. I meant legacy members already in an existing website. As in people have members already and they are adding this code... some might not have usernames as emails - but if you were just to create a new site and only use this code (and not break it by creating members in the back end )..

**Comment by nul800sebastiaan** [comment]
Fair enough!
