### ISSUE TITLE
Add CSRF protection to forms

### ISSUE THREAD

**Issue by AndyButland** [cheeseytoastie/UmbMembersFullTutorial#5]
Firstly thanks for making this available - it's a useful reference.  That said, given it'll likely be used as that, would be good to demonstrate best practice for protecting against CSRF attacks.

Namely `@Html.AntiForgeryToken()` in the forms.

And `[ValidateAntiForgeryToken]` decorating the controller actions that process the form posts.

**Comment by cheeseytoastie** [comment]
Great spot, just added. Hopefully I've put it all in the right place.
